apiVersion: 1

datasources:
  - id: 1
    orgId: 1
    name: ClickHouse
    type: vertamedia-clickhouse-datasource
    typeLogoUrl: public/plugins/vertamedia-clickhouse-datasource/img/clickhouse_logo.svg
    access: proxy
    url: http://clickhouse-server:8123
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData: {}
    readOnly: false
